default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  url: <%= ENV["DATABASE_URL"] %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", nil) %>


development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "vene_jewelry_development") %>


test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME_TEST", "vene_jewelry_test") %>


production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "vene_jewelry_production") %>
